name: builddev
on:
  pull_request:
    branches: [ "staging" ]
    types: [ closed ]
jobs:
  merge_job:
    name: build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: ssh to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd ../enaspicloud
          git pull
          docker stop enaspicloud
          docker build . -t enaspicloud
          docker run -itd --rm --name enaspicloud -p 3358:80 enaspicloud
          docker rmi $(docker images --filter 'dangling=true' -q)